baseURL: https://maguirekrist.com/
languageCode: en-us
title: Maguire Krist
theme: ["PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

params:
  env: production
  description: "Maguire's Personal Site"
  author: ["Me"]

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  homeInfoParams:
    Title: "PaperMod's Demo"
    Content: >
      👋 Welcome to demo page of Hugo's theme PaperMod!

      - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

      - Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .

      - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).
  socialIcons:
      - name: github
        title: Maguire's Github
        url: "https://github.com/maguirekrist"
      - name: LinkedIn
        title: Maguire's LinkedIn
        url: "https://www.linkedin.com/in/maguire-k-82825abb/"