baseURL: https://maguirekrist.com/
languageCode: en-us
title: Maguire Krist
theme: ["nostyleplease"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

caches:
  images:
    dir: :cacheDir/images

menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10

services:
  googleAnalytics:
    id: G-9W9N6D36FS


params:
  env: production
  description: "Maguire's Personal Site"
  author: ["Me"]

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  homeInfoParams:
    Title: "Hello"
    Content: >
      .NET full-stack developer by day, indie hacker & systems engineer at night.
  socialIcons:
      - name: github
        title: Maguire's Github
        url: "https://github.com/maguirekrist"
      - name: LinkedIn
        title: Maguire's LinkedIn
        url: "https://www.linkedin.com/in/maguirekrist"
      - name: email
        url: "mailto:maguirekrist@gmail.com?subject=Hello%20from%20your%20site"